Add support for do/raw-txn
fulcrologic/fulcro-rad-datomic pull request #22
Opened 2023-08-19 22:54 UTC by holyjak

Enable users of the save and delete middlewares to add to the generated transactions by adding a list of transaction data under the key do/raw-txn into Pathom env.

Also switched to the latest com.datomic/local and got rid of thus unnecessary `dev-local-tu`

(Updating to com.datomic/peer is blocked by datomock)

2023-08-19 23:03 UTC, holyjak commented on deps.edn
> +                            ;;  com.datomic/peer          {:mvn/version "1.0.6735" ; TODO use when datamock > 0.2.2 is out
see https://clojurians.slack.com/archives/C03RZMDSH/p1692484114205989

2023-08-20 17:02 UTC, awkay requested changes

2023-08-20 17:02 UTC, awkay commented on src/main/com/fulcrologic/rad/database_adapters/datomic_options.cljc
> +      (assoc do/raw-txn [(list 'my.txn.fns/ensure-no-prior-order user) ; check pre-condition
This is not really meant to go in at the *pathom* layer (at least not primarily). It is meant to be installed as part of the middleware stack. To that end, perhaps it makes sense to add a datomic-common helper function like `(append-to-raw-transaction mw-env) -> updated-env`?

I mean, I guess it is *ok* to put it in the pathom layer...in either case, though, the implementation should always assume others might be using it in middleware and should be appending to what is already there:

```
(update env do/raw-txn (fnil into []) my-txn)
```

2023-08-21 18:46 UTC, awkay approved these changes

2023-08-21 18:47 UTC, merged