Add Datomic Cloud support
fulcrologic/fulcro-rad-datomic pull request #7
Opened 2020-04-17 06:19 UTC by mdhaney

I ran into too many problems trying to use the same adapter for both as we discussed, but was able to get Cloud working using its own adapter.

2020-04-18 23:48 UTC, awkay commented on src/main/com/fulcrologic/rad/database_adapters/datomic_cloud.clj
> -  ["com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool"
Please don't delete things like this.

2020-04-18 23:54 UTC, awkay requested changes

2020-04-18 23:54 UTC, awkay commented on src/main/com/fulcrologic/rad/database_adapters/datomic_cloud.clj
> +(def type-map
A *lot* of code duplication in this ns...why not move a lot of this stuff to a Datomic common ns.

2020-04-18 23:55 UTC, awkay commented on deps.edn
> +           datomic-client-memdb       {:mvn/version "1.0.2"}
Is this required everywhere?  Why is this a common dependency?

2020-04-18 23:56 UTC, awkay commented on src/test/com/fulcrologic/rad/test_schema_cloud/address.clj
> +(ns com.fulcrologic.rad.test-schema-cloud.address
Was there a real need to create new attrs for tests?  aren't there already attrs for tests?

2020-06-16 13:52 UTC, awkay commented
Let me know if you still want to make this contribution. It needs a little cleanup still.

2020-07-21 16:13 UTC, awkay commented
I'll reopen this if/when the remaining work is done.

2020-08-03 02:51 UTC, tylernisonoff commented
I was experimenting with the PR in hopes of being able to help get it over the finish line

I've gotten a bunch working working on the RAD demo, except the automatic-resolvers aren't working
It seems to be the `pull-many` implementation -- I always get [nil nil ...] back for queries that work with the `d/pull`  if I'm just using one id

I'm using the new [dev-local](https://docs.datomic.com/cloud/dev-local.html) library for local development with cloud , i suppose theres a chance the query is getting evaluated incorrectly there, but not sure. 

I'm fairly new to datomic so still learning complex datalog queries, but will keep experimenting to see if i can get `pull-many` working

2020-08-03 16:56 UTC, awkay commented
The client API (which cloud uses) does not have a pull-many. https://docs.datomic.com/client-api/datomic.client.api.html#var-pull

I think you have to write a wrapper to implement it yourself...I thought that was already there in the PR. I thought the main problem in the PR was that it was kinda messy.

2020-08-03 16:59 UTC, tylernisonoff commented
> I think you have to write a wrapper to implement it yourself...I thought that was already there in the PR.

Yes, but the implementation isn't working for me, so I'm gonna try to write one myself / figure out whats going on with the implementation in the PR. 

> I thought the main problem in the PR was that it was kinda messy.

I'll also look into cleaning it up. Maintaining two adapters seems less ideal, I'll look into if theres a way to unify the adapters, and if not, see how else I can clean it up.

2020-08-04 02:28 UTC, tylernisonoff commented
Update: Turns out the pull-many implementation is correct! The error was related to my translation of the queries in the demo to a client-compatible syntax. For example:

[In cloud](https://docs.datomic.com/cloud/query/query-data-reference.html#find-specs), only find rel is support for the find-spec  

So I had to translate the demo queries from something like:

```
(defn get-all-categories
  [env query-params]
  (if-let [db (some-> (get-in env [::datomic/databases :production]) deref)]
    (let [ids (d/q '[:find [?id ...]
                     :where
                     [?e :category/label]
                     [?e :category/id ?id]] db)]
      (mapv (fn [id] {:category/id id}) ids))
    (log/error "No database atom for production schema!")))
```

to

```
(defn get-all-categories
  [env query-params]
  (if-let [db (some-> (get-in env [::datomic/databases :production]) deref)]
    (let [ids (d/q '[:find ?id
                     :where
                     [?e :category/label]
                     [?e :category/id ?id]] db)]
      (->> ids
        flatten
        (mapv (fn [id] {:category/id id}))))
    (log/error "No database atom for production schema!")))
```

[Here's a similar PR in the pathom-datomic repo](https://github.com/wilkerlucio/pathom-datomic/pull/1/files)


Given that, this PR is working. I'll look this week into cleaning it up, and seeing if the adapter can be unified.

2020-08-04 03:06 UTC, tylernisonoff commented
Hmm, yeah its definitely going to be difficult to get these sharing the same adaptor.

I think the first step would be getting the current adapter to use the client API
["On-Prem supports client or peer access, while Cloud supports only client access."](https://docs.datomic.com/on-prem/moving-to-cloud.html)

the client API does not allow transactors, so not sure what that means for `ensure-transactor-functions!`... 

Alternatively, I can try to migrate most of this to a common namespace, but that will likely break some compatibility (for example, references to `database-adapters.datomic/attribute-schema` would probably go under `database-adapters.datomic-shared/attribute-schema`, or we'd move the adapter to `database-adatpers.datomic-on-prem` and leave `datomic/` for shared stuff).

@awkay if you have advice on how to proceed (namely, if you think we can reasonably modify this logic to fit within the client API or should just refactor to a new ns), let me know! I understand if you don't have time as well.

2020-08-04 03:23 UTC, awkay commented
So, there is no need to make it the *same* adapter. I was just hoping that the rote code duplication could be removed. E.g. move anything that can be shared to a common ns, and require it in both.

2020-08-04 23:53 UTC, tylernisonoff commented
>  Also, use the main ns for the keyword option namespace...there is no need to make diff nses for the keywords that have the same meaning. They can just be in the datomic ns.

@awkay  just to make sure I understand (I'm somewhat new to this stuff, so apologies if I have a misunderstanding):

 we want to keep options such as `:com.fulcrologic.rad.database-adapters.datomic/attribute-schema` in the datomic namespace, and use this `.../database-adapaters.datomic` keyspace across both adapters. 

Since theres a lot of shared functionality across the two adapters that makes use of these keywords, these functions would be moved to a common namespace, and we'd have to reference the keywords using the full  path `:com.fulcrologic.rad.database-adapters.datomic/..` 

Is that what you'd like?

Another option I see could be using the common namespace to house these options, which would clean up the internal code here that references it. Additionally, end-users of the library could require the common namespace to make working with these keywords easier. 

Happy to implement whichever you prefer.

2020-08-05 02:09 UTC, awkay commented
So, if you look at the other RAD libraries: there are -options nses...i.e. form-options. These are nothing more than defs with docstrings whose values are keywords. Ideally we'd adopt that in this library as well, I just haven't had the time.

So, in terms of the keywords, that's what I'd do for ALL versions of Datomic...one options ns that describes what the keys mean. You don't have to do that, but it would be apprecaited. none of the actualy kws should change from their current fully-qualified name, because that would be a breaking change. Again, look at how I did it in the main RAD library.

The main thing from this PR was what I said about in the inline comments: there are a number of functions that just got copied willy-nilly into a new ns...pure duplication. I'd like those to have some common ns. I realize it can't all be one ns, or we have require problems, and there probably has to be some dynamic require stuff to even make the whole thing workable.

So a `datomic-common` ns seems right.

2020-08-05 13:18 UTC, tylernisonoff commented
got it, makes sense 👌

2020-08-05 16:21 UTC, mdhaney commented
So I had originally tried to separate the common functions and reuse them, but it's tricky.  The problem is that inevitably all those functions need to use the Datomic API, which differs between client/cloud and peer.  In an earlier iteration of this adapter I tried to solve that problem using protocols, so the common functions are always calling the protocol methods.  You then have a namespace for each datomic client type that implements the protocol using the correct library.  

At some point I removed that layer, although I don't recall exactly why.  It was probably because I was trying to track down other issues and wanted to remove as much complexity as possible until I had the basic functionality correct, and then was time crunched and never added back the abstraction over the datomic libraries.

Just wanted to let you know what you're dealing with and how you might approach it.  Unfortunately I'm not in a position to make the changes myself right now, and it will likely be several months before I have the free time to do that.  But I can try to help answer questions or give tips as much as possible to whoever wants to fix this.

2020-08-16 02:02 UTC, tylernisonoff commented
Opened a new PR here: https://github.com/fulcrologic/fulcro-rad-datomic/pull/9

2020-08-18 02:25 UTC, awkay commented
closed in favor of #9

2020-08-18 02:25 UTC, closed without merging